[build]
  publish = "build/web"
  command = """
    # Install Flutter
    apt-get update
    apt-get install -y unzip xz-utils git
    git clone https://github.com/flutter/flutter.git
    export PATH="$FLUTTER_ROOT/flutter/bin:$PATH"
    flutter precache

    # Build Flutter web app
    flutter build web
  """

[build.environment]
  FLUTTER_ROOT = "/opt/build/repo/flutter"