[build]
  publish = "build/web"
  command = """
    # Install Flutter
    git clone https://github.com/flutter/flutter.git
    export PATH=$PWD/flutter/bin:$PATH
    flutter precache

    # Build Flutter web app
    flutter build web
  """